// ArabDramaTV Database - Asian Dramas for Arabic Audience
// Source: arabdramatv.net / K-Dramas, C-Dramas, Thai dramas

const arabdramatvContent = [
    // K-DRAMAS (Korean)
    {id: 300, tmdbId: "92749", title: "Moon Lovers: Scarlet Heart Ryeo", thumbnail: "https://image.tmdb.org/t/p/original/1lLlKGLCsrlvKvHgJHsjLd95vCH.jpg", year: 2016, genre: ["Romance", "Drama"], rating: 92, description: "Una mujer moderna viaja al pasado a la era Goryeo.", region: "Asia", country: "Corea del Sur", type: "series", language: "Coreano", source: "arabdramatv"},
    {id: 301, tmdbId: "66788", title: "Goblin", thumbnail: "https://image.tmdb.org/t/p/original/8GfP1LshyiRMkWHDMlSTGSpWuQT.jpg", year: 2016, genre: ["Fantasy", "Romance"], rating: 95, description: "Un goblin inmortal busca a su novia humana.", region: "Asia", country: "Corea del Sur", type: "series", language: "Coreano", source: "arabdramatv"},
    {id: 302, tmdbId: "76663", title: "Crash Landing on You", thumbnail: "https://image.tmdb.org/t/p/original/jlhXNdvLIj8KPxvJkHMmL0UvDjP.jpg", year: 2019, genre: ["Romance", "Comedy"], rating: 94, description: "Una heredera surcoreana aterriza en Corea del Norte.", region: "Asia", country: "Corea del Sur", type: "series", language: "Coreano", source: "arabdramatv"},
    {id: 303, tmdbId: "97180", title: "It's Okay to Not Be Okay", thumbnail: "https://image.tmdb.org/t/p/original/jR1uLNjhE5iKSMVIxQH4dYeON63.jpg", year: 2020, genre: ["Romance", "Drama"], rating: 93, description: "Un trabajador psiquiátrico conoce a una escritora antisocial.", region: "Asia", country: "Corea del Sur", type: "series", language: "Coreano", source: "arabdramatv"},
    {id: 304, tmdbId: "84773", title: "Vincenzo", thumbnail: "https://image.tmdb.org/t/p/original/dvXJgEDQXhL9Ouot2WkBHpQiHGd.jpg", year: 2021, genre: ["Crime", "Comedy"], rating: 91, description: "Un abogado de la mafia italiana regresa a Corea.", region: "Asia", country: "Corea del Sur", type: "series", language: "Coreano", source: "arabdramatv"},
    {id: 305, tmdbId: "100088", title: "Hospital Playlist", thumbnail: "https://image.tmdb.org/t/p/original/esIDKJb7M7bxdCfoJiWY7VXdxvF.jpg", year: 2020, genre: ["Drama", "Comedy"], rating: 92, description: "Cinco médicos que son amigos desde la universidad.", region: "Asia", country: "Corea del Sur", type: "series", language: "Coreano", source: "arabdramatv"},
    {id: 306, tmdbId: "93405", title: "Reply 1988", thumbnail: "https://image.tmdb.org/t/p/original/qYpJxFgXq5kk3b8K7W5q5vR7z8v.jpg", year: 2015, genre: ["Drama", "Comedy"], rating: 96, description: "La vida de cinco familias en un barrio de Seúl en 1988.", region: "Asia", country: "Corea del Sur", type: "series", language: "Coreano", source: "arabdramatv"},
    {id: 307, tmdbId: "110316", title: "Extraordinary Attorney Woo", thumbnail: "https://image.tmdb.org/t/p/original/xQmvpNlzEhj0JQxkXsSLFKSQp3e.jpg", year: 2022, genre: ["Drama", "Comedy"], rating: 94, description: "Una abogada autista brillante navega su carrera.", region: "Asia", country: "Corea del Sur", type: "series", language: "Coreano", source: "arabdramatv"},
    {id: 308, tmdbId: "203057", title: "My Love from the Star", thumbnail: "https://image.tmdb.org/t/p/original/y3H8N7Cg7M8pR8qPxnZMSTwUlCE.jpg", year: 2013, genre: ["Romance", "Fantasy"], rating: 90, description: "Un alienígena se enamora de una actriz.", region: "Asia", country: "Corea del Sur", type: "series", language: "Coreano", source: "arabdramatv"},
    {id: 309, tmdbId: "85552", title: "Business Proposal", thumbnail: "https://image.tmdb.org/t/p/original/lNlxOUS7gprIGsVxQlzGHIchRRi.jpg", year: 2022, genre: ["Romance", "Comedy"], rating: 89, description: "Una empleada va a una cita a ciegas en lugar de su amiga.", region: "Asia", country: "Corea del Sur", type: "series", language: "Coreano", source: "arabdramatv"},

    // C-DRAMAS (Chinese)
    {id: 320, tmdbId: "85271", title: "The Untamed", thumbnail: "https://image.tmdb.org/t/p/original/ewwqFSZGFuSH8q0wXpXHZtQ8F1K.jpg", year: 2019, genre: ["Fantasy", "Adventure"], rating: 93, description: "Dos cultivadores resuelven misterios sobrenaturales.", region: "Asia", country: "China", type: "series", language: "Chino", source: "arabdramatv"},
    {id: 321, tmdbId: "94605", title: "Word of Honor", thumbnail: "https://image.tmdb.org/t/p/original/4XCNXqQOTjUNsN5lhAVJLdP8N4J.jpg", year: 2021, genre: ["Fantasy", "Action"], rating: 91, description: "Dos maestros de artes marciales forman una alianza.", region: "Asia", country: "China", type: "series", language: "Chino", source: "arabdramatv"},
    {id: 322, tmdbId: "61174", title: "Nirvana in Fire", thumbnail: "https://image.tmdb.org/t/p/original/r0tg2jb0kXAOVNqxQ9e6YJhGIJm.jpg", year: 2015, genre: ["Drama", "History"], rating: 95, description: "Un estratega planea su venganza desde las sombras.", region: "Asia", country: "China", type: "series", language: "Chino", source: "arabdramatv"},
    {id: 323, tmdbId: "63174", title: "Love O2O", thumbnail: "https://image.tmdb.org/t/p/original/xXjE2n1rQlRTaH2QOsxZoFqRX3T.jpg", year: 2016, genre: ["Romance", "Comedy"], rating: 88, description: "Romance entre dos jugadores de videojuegos.", region: "Asia", country: "China", type: "series", language: "Chino", source: "arabdramatv"},
    {id: 324, tmdbId: "97639", title: "You Are My Glory", thumbnail: "https://image.tmdb.org/t/p/original/aM9pJNVQZPEgCNkKJAL7ZLK0PKY.jpg", year: 2021, genre: ["Romance", "Drama"], rating: 89, description: "Una actriz reconecta con su amor de la escuela.", region: "Asia", country: "China", type: "series", language: "Chino", source: "arabdramatv"},

    // THAI DRAMAS
    {id: 340, tmdbId: "90669", title: "2gether: The Series", thumbnail: "https://image.tmdb.org/t/p/original/xqv7hKgwcrWcQqnLRkVnYx3g9OJ.jpg", year: 2020, genre: ["Romance", "Comedy"], rating: 88, description: "Un estudiante finge ser novio de otro para evitar a un admirador.", region: "Asia", country: "Tailandia", type: "series", language: "Tailandés", source: "arabdramatv"},
    {id: 341, tmdbId: "102174", title: "Bad Buddy", thumbnail: "https://image.tmdb.org/t/p/original/hF8V8mI7WXAuA8yGxPrQVLJGGBF.jpg", year: 2021, genre: ["Romance", "Comedy"], rating: 90, description: "Dos vecinos rivales descubren sentimientos inesperados.", region: "Asia", country: "Tailandia", type: "series", language: "Tailandés", source: "arabdramatv"},
    {id: 342, tmdbId: "85271", title: "F4 Thailand", thumbnail: "https://image.tmdb.org/t/p/original/jLkV1k5vLCh4GHxl25JbLZQsHrz.jpg", year: 2021, genre: ["Romance", "Drama"], rating: 86, description: "Una chica becada enfrenta a los chicos más ricos de la escuela.", region: "Asia", country: "Tailandia", type: "series", language: "Tailandés", source: "arabdramatv"},
    {id: 343, tmdbId: "97268", title: "Girl from Nowhere", thumbnail: "https://image.tmdb.org/t/p/original/geCRueV3Qe0bShT6IhgEHCHiUDW.jpg", year: 2018, genre: ["Thriller", "Drama"], rating: 87, description: "Una misteriosa estudiante expone secretos oscuros.", region: "Asia", country: "Tailandia", type: "series", language: "Tailandés", source: "arabdramatv"},

    // JAPANESE DRAMAS
    {id: 360, tmdbId: "65942", title: "Alice in Borderland", thumbnail: "https://image.tmdb.org/t/p/original/20mOwAAPwZ1vLQkw0fvuQHiG7bO.jpg", year: 2020, genre: ["Thriller", "Sci-Fi"], rating: 91, description: "Gamers atrapados en un Tokio abandonado deben jugar para sobrevivir.", region: "Asia", country: "Japón", type: "series", language: "Japonés", source: "arabdramatv"},
    {id: 361, tmdbId: "60625", title: "Hana Yori Dango", thumbnail: "https://image.tmdb.org/t/p/original/b8FKZY8Y7yDBCOSLCCHMNY8LPGQ.jpg", year: 2005, genre: ["Romance", "Comedy"], rating: 89, description: "Una chica pobre entra a una escuela de élite.", region: "Asia", country: "Japón", type: "series", language: "Japonés", source: "arabdramatv"},
    {id: 362, tmdbId: "203057", title: "Midnight Diner: Tokyo Stories", thumbnail: "https://image.tmdb.org/t/p/original/afkFRXYw0utdN2s3oWnZJbcxQNz.jpg", year: 2016, genre: ["Drama", "Comedy"], rating: 90, description: "Historias de los clientes de un pequeño restaurante nocturno.", region: "Asia", country: "Japón", type: "series", language: "Japonés", source: "arabdramatv"}
];

// Export
if (typeof module !== 'undefined' && module.exports) {
    module.exports = arabdramatvContent;
}
