// Cinecalidad Database - Latin American and Spanish Content
// Source: cinecalidad.com / Spanish dubbed and Latin content

const cinecalidadContent = [
    // LATIN AMERICAN HITS
    {id: 800, tmdbId: "272", title: "Batman Begins", thumbnail: "https://image.tmdb.org/t/p/original/8RW2runSEc34IwKN2D1aPcJd2UL.jpg", year: 2005, genre: ["Action", "Crime"], rating: 92, description: "Bruce Wayne se convierte en Batman para salvar Gotham.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cinecalidad"},
    {id: 801, tmdbId: "155", title: "The Dark Knight", thumbnail: "https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg", year: 2008, genre: ["Action", "Crime"], rating: 98, description: "Batman enfrenta al Joker en una batalla por el alma de Gotham.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cinecalidad"},
    {id: 802, tmdbId: "49026", title: "The Dark Knight Rises", thumbnail: "https://image.tmdb.org/t/p/original/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg", year: 2012, genre: ["Action", "Crime"], rating: 94, description: "Batman regresa para salvar Gotham de Bane.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cinecalidad"},
    {id: 803, tmdbId: "27205", title: "Inception", thumbnail: "https://image.tmdb.org/t/p/original/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg", year: 2010, genre: ["Sci-Fi", "Thriller"], rating: 96, description: "Ladrones roban secretos del subconsciente durante los sueños.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cinecalidad"},
    {id: 804, tmdbId: "157336", title: "Interstellar", thumbnail: "https://image.tmdb.org/t/p/original/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", year: 2014, genre: ["Sci-Fi", "Drama"], rating: 97, description: "Exploradores viajan a través de un agujero de gusano en el espacio.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cinecalidad"},
    {id: 805, tmdbId: "429617", title: "Spider-Man: Far From Home", thumbnail: "https://image.tmdb.org/t/p/original/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg", year: 2019, genre: ["Action", "Adventure"], rating: 89, description: "Peter Parker enfrenta a Mysterio en Europa.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cinecalidad"},
    {id: 806, tmdbId: "315635", title: "Spider-Man: Homecoming", thumbnail: "https://image.tmdb.org/t/p/original/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg", year: 2017, genre: ["Action", "Adventure"], rating: 91, description: "Peter Parker equilibra su vida de estudiante y superhéroe.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cinecalidad"},
    {id: 807, tmdbId: "118340", title: "Guardians of the Galaxy", thumbnail: "https://image.tmdb.org/t/p/original/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg", year: 2014, genre: ["Action", "Adventure"], rating: 93, description: "Un grupo de inadaptados salva la galaxia.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cinecalidad"},
    {id: 808, tmdbId: "283995", title: "Guardians of the Galaxy Vol. 2", thumbnail: "https://image.tmdb.org/t/p/original/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg", year: 2017, genre: ["Action", "Adventure"], rating: 91, description: "Los Guardianes descubren el linaje de Peter Quill.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cinecalidad"},
    {id: 809, tmdbId: "24428", title: "The Avengers", thumbnail: "https://image.tmdb.org/t/p/original/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg", year: 2012, genre: ["Action", "Adventure"], rating: 95, description: "Los héroes más poderosos de la Tierra se unen.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cinecalidad"},

    // SPANISH SERIES
    {id: 820, tmdbId: "71712", title: "The Witcher", thumbnail: "https://image.tmdb.org/t/p/original/7vjaCdMw15FEbXyLQTVa04URsPm.jpg", year: 2019, genre: ["Fantasy", "Action"], rating: 90, description: "Geralt de Rivia, un cazador de monstruos solitario.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "cinecalidad"},
    {id: 821, tmdbId: "1399", title: "Game of Thrones", thumbnail: "https://image.tmdb.org/t/p/original/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg", year: 2011, genre: ["Drama", "Fantasy"], rating: 96, description: "Nueve familias nobles luchan por el control de Westeros.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "cinecalidad"},
    {id: 822, tmdbId: "82856", title: "The Mandalorian", thumbnail: "https://image.tmdb.org/t/p/original/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg", year: 2019, genre: ["Sci-Fi", "Adventure"], rating: 93, description: "Un cazarrecompensas viaja por la galaxia con Grogu.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "cinecalidad"},
    {id: 823, tmdbId: "1418", title: "The Big Bang Theory", thumbnail: "https://image.tmdb.org/t/p/original/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg", year: 2007, genre: ["Comedy"], rating: 88, description: "Cuatro nerds científicos y su vecina Penny.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "cinecalidad"},
    {id: 824, tmdbId: "1396", title: "Breaking Bad", thumbnail: "https://image.tmdb.org/t/p/original/ggFHVNu6YYI5L9pCfOacjizRGt.jpg", year: 2008, genre: ["Crime", "Drama"], rating: 99, description: "Un profesor de química se convierte en fabricante de metanfetaminas.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "cinecalidad"}
];

// Export
if (typeof module !== 'undefined' && module.exports) {
    module.exports = cinecalidadContent;
}
