// Cuevana Database - Spanish and International Content
// Source: cuevana.com / Movies and series in Spanish

const cuevanaContent = [
    // BLOCKBUSTERS
    {id: 900, tmdbId: "209112", title: "Batman v Superman: Dawn of Justice", thumbnail: "https://image.tmdb.org/t/p/original/5UsK3grJvtQrtzEgqNlDljJW96w.jpg", year: 2016, genre: ["Action", "Adventure"], rating: 84, description: "Batman y Superman se enfrentan mientras surge una nueva amenaza.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cuevana"},
    {id: 901, tmdbId: "141052", title: "Justice League", thumbnail: "https://image.tmdb.org/t/p/original/eifGNCSDuxJeS1loAXil5bIGgvC.jpg", year: 2017, genre: ["Action", "Adventure"], rating: 81, description: "Batman y Wonder Woman reclutan superhéroes para salvar el mundo.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cuevana"},
    {id: 902, tmdbId: "338762", title: "Bloodshot", thumbnail: "https://image.tmdb.org/t/p/original/8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg", year: 2020, genre: ["Action", "Sci-Fi"], rating: 79, description: "Un soldado resucitado busca venganza con superpoderes.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cuevana"},
    {id: 903, tmdbId: "791373", title: "Zack Snyder's Justice League", thumbnail: "https://image.tmdb.org/t/p/original/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg", year: 2021, genre: ["Action", "Adventure"], rating: 92, description: "La versión del director de Justice League.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cuevana"},
    {id: 904, tmdbId: "287947", title: "Shazam!", thumbnail: "https://image.tmdb.org/t/p/original/xnopI5Xtky18MPhK40cZAGAOVeV.jpg", year: 2019, genre: ["Action", "Comedy"], rating: 88, description: "Un niño puede convertirse en superhéroe adulto diciendo 'Shazam'.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cuevana"},
    {id: 905, tmdbId: "603692", title: "John Wick: Chapter 4", thumbnail: "https://image.tmdb.org/t/p/original/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg", year: 2023, genre: ["Action", "Thriller"], rating: 93, description: "John Wick enfrenta a sus enemigos más mortales.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cuevana"},
    {id: 906, tmdbId: "458156", title: "John Wick: Chapter 3 - Parabellum", thumbnail: "https://image.tmdb.org/t/p/original/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg", year: 2019, genre: ["Action", "Thriller"], rating: 91, description: "John Wick es perseguido por asesinos en todo el mundo.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cuevana"},
    {id: 907, tmdbId: "324857", title: "Spider-Man: Into the Spider-Verse", thumbnail: "https://image.tmdb.org/t/p/original/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg", year: 2018, genre: ["Animation", "Action"], rating: 97, description: "Miles Morales se convierte en Spider-Man en su dimensión.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "cuevana"},
    {id: 908, tmdbId: "508965", title: "Klaus", thumbnail: "https://image.tmdb.org/t/p/original/q125RHUDgR4gjwh1QkfYuJLYkL.jpg", year: 2019, genre: ["Animation", "Comedy"], rating: 92, description: "Un cartero y un fabricante de juguetes crean la leyenda de Santa Claus.", region: "Hollywood", country: "España", type: "movie", language: "Español", source: "cuevana"},

    // NETFLIX ORIGINALS
    {id: 920, tmdbId: "80025", title: "Stranger Things", thumbnail: "https://image.tmdb.org/t/p/original/49WJfeN0moxb9IPfGn8AIqMGskD.jpg", year: 2016, genre: ["Drama", "Sci-Fi"], rating: 94, description: "Niños de un pueblo enfrentan fuerzas sobrenaturales.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "cuevana"},
    {id: 921, tmdbId: "63174", title: "Lucifer", thumbnail: "https://image.tmdb.org/t/p/original/ekZobS8isE6mA53RAiGDG93hBxL.jpg", year: 2016, genre: ["Crime", "Fantasy"], rating: 90, description: "El diablo abandona el infierno y se convierte en consultor policial.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "cuevana"},
    {id: 922, tmdbId: "69050", title: "Riverdale", thumbnail: "https://image.tmdb.org/t/p/original/wRbjVBdDo5qHAEOVYoMWpM58FSA.jpg", year: 2017, genre: ["Drama", "Mystery"], rating: 83, description: "Archie y sus amigos investigan secretos oscuros en su pueblo.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "cuevana"},
    {id: 923, tmdbId: "65820", title: "The Flash", thumbnail: "https://image.tmdb.org/t/p/original/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg", year: 2014, genre: ["Action", "Sci-Fi"], rating: 88, description: "Barry Allen usa su súper velocidad para combatir el crimen.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "cuevana"},
    {id: 924, tmdbId: "60735", title: "The 100", thumbnail: "https://image.tmdb.org/t/p/original/wcaDIAG1QdXQLRaj4vC1EFdBT2.jpg", year: 2014, genre: ["Sci-Fi", "Drama"], rating: 87, description: "100 jóvenes son enviados a la Tierra post-apocalíptica.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "cuevana"},
    {id: 925, tmdbId: "62286", title: "Fear the Walking Dead", thumbnail: "https://image.tmdb.org/t/p/original/58PON1OrnBiX6CqEHt3AhWmyZ5Y.jpg", year: 2015, genre: ["Horror", "Drama"], rating: 84, description: "El comienzo del apocalipsis zombie en Los Ángeles.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "cuevana"}
];

// Export
if (typeof module !== 'undefined' && module.exports) {
    module.exports = cuevanaContent;
}
