// EmbedSu Database - European and Independent Cinema
// Source: embed.su / European Films and Arthouse

const embedsuContent = [
    // EUROPEAN CINEMA
    {id: 500, tmdbId: "466420", title: "Parasite", thumbnail: "https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", year: 2019, genre: ["Thriller", "Drama"], rating: 96, description: "Una familia pobre infiltra la vida de una familia rica.", region: "Europa", country: "Corea del Sur", type: "movie", language: "Coreano", source: "embedsu"},
    {id: 501, tmdbId: "508442", title: "Soul", thumbnail: "https://image.tmdb.org/t/p/original/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg", year: 2020, genre: ["Animation", "Drama"], rating: 94, description: "Un músico de jazz busca recuperar su pasión por la vida.", region: "Europa", country: "Estados Unidos", type: "movie", language: "Inglés", source: "embedsu"},
    {id: 502, tmdbId: "497698", title: "Black Widow", thumbnail: "https://image.tmdb.org/t/p/original/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg", year: 2021, genre: ["Action", "Adventure"], rating: 85, description: "Natasha Romanoff enfrenta su oscuro pasado.", region: "Europa", country: "Estados Unidos", type: "movie", language: "Inglés", source: "embedsu"},
    {id: 503, tmdbId: "524434", title: "Eternals", thumbnail: "https://image.tmdb.org/t/p/original/bcCBq9N1EMo3daNIjWJ8kYvrQm6.jpg", year: 2021, genre: ["Action", "Fantasy"], rating: 82, description: "Seres inmortales salen de las sombras para proteger la Tierra.", region: "Europa", country: "Estados Unidos", type: "movie", language: "Inglés", source: "embedsu"},
    {id: 504, tmdbId: "566525", title: "Shang-Chi and the Legend of the Ten Rings", thumbnail: "https://image.tmdb.org/t/p/original/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg", year: 2021, genre: ["Action", "Fantasy"], rating: 89, description: "Shang-Chi debe enfrentarse a su pasado y la organización de su padre.", region: "Europa", country: "Estados Unidos", type: "movie", language: "Inglés", source: "embedsu"},
    {id: 505, tmdbId: "617653", title: "No Time to Die", thumbnail: "https://image.tmdb.org/t/p/original/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg", year: 2021, genre: ["Action", "Thriller"], rating: 87, description: "James Bond sale del retiro para una última misión.", region: "Europa", country: "Reino Unido", type: "movie", language: "Inglés", source: "embedsu"},
    {id: 506, tmdbId: "580489", title: "Venom: Let There Be Carnage", thumbnail: "https://image.tmdb.org/t/p/original/1MJNcPZy46hIy2CmSqOeru0yr5C.jpg", year: 2021, genre: ["Action", "Sci-Fi"], rating: 83, description: "Eddie Brock intenta revivir su carrera mientras enfrenta a Carnage.", region: "Europa", country: "Estados Unidos", type: "movie", language: "Inglés", source: "embedsu"},
    {id: 507, tmdbId: "634649", title: "Spider-Man: No Way Home", thumbnail: "https://image.tmdb.org/t/p/original/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg", year: 2021, genre: ["Action", "Adventure"], rating: 95, description: "Spider-Man busca ayuda del Doctor Strange con consecuencias devastadoras.", region: "Europa", country: "Estados Unidos", type: "movie", language: "Inglés", source: "embedsu"},
    {id: 508, tmdbId: "460465", title: "Mortal Kombat", thumbnail: "https://image.tmdb.org/t/p/original/nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg", year: 2021, genre: ["Action", "Fantasy"], rating: 81, description: "Luchadores MMA descubren sus destinos en un torneo.", region: "Europa", country: "Estados Unidos", type: "movie", language: "Inglés", source: "embedsu"},
    {id: 509, tmdbId: "527774", title: "Raya and the Last Dragon", thumbnail: "https://image.tmdb.org/t/p/original/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg", year: 2021, genre: ["Animation", "Adventure"], rating: 88, description: "Una guerrera busca al último dragón para salvar su mundo.", region: "Europa", country: "Estados Unidos", type: "movie", language: "Inglés", source: "embedsu"},

    // FRENCH CINEMA
    {id: 520, tmdbId: "508947", title: "Turning Red", thumbnail: "https://image.tmdb.org/t/p/original/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg", year: 2022, genre: ["Animation", "Comedy"], rating: 87, description: "Una niña de 13 años se convierte en un panda rojo gigante.", region: "Europa", country: "Estados Unidos", type: "movie", language: "Inglés", source: "embedsu"},
    {id: 521, tmdbId: "476669", title: "The King's Man", thumbnail: "https://image.tmdb.org/t/p/original/aq4Pwv5Xeuvj6HZKtxyd23e6bE9.jpg", year: 2021, genre: ["Action", "Adventure"], rating: 84, description: "El origen de la primera agencia de inteligencia independiente.", region: "Europa", country: "Reino Unido", type: "movie", language: "Inglés", source: "embedsu"},
    {id: 522, tmdbId: "568124", title: "Encanto", thumbnail: "https://image.tmdb.org/t/p/original/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg", year: 2021, genre: ["Animation", "Comedy"], rating: 91, description: "Una familia mágica vive en una casa encantada en Colombia.", region: "Europa", country: "Estados Unidos", type: "movie", language: "Español", source: "embedsu"},
    {id: 523, tmdbId: "675353", title: "Sonic the Hedgehog 2", thumbnail: "https://image.tmdb.org/t/p/original/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg", year: 2022, genre: ["Action", "Adventure"], rating: 86, description: "Sonic y Tails se enfrentan a Knuckles y al Dr. Robotnik.", region: "Europa", country: "Estados Unidos", type: "movie", language: "Inglés", source: "embedsu"},
    {id: 524, tmdbId: "335787", title: "Uncharted", thumbnail: "https://image.tmdb.org/t/p/original/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg", year: 2022, genre: ["Action", "Adventure"], rating: 84, description: "Nathan Drake y Sully buscan el tesoro de Magallanes.", region: "Europa", country: "Estados Unidos", type: "movie", language: "Inglés", source: "embedsu"}
];

// Export
if (typeof module !== 'undefined' && module.exports) {
    module.exports = embedsuContent;
}
