// HDToday Database - General Content (Hollywood, Europe, Anime, etc.)
// Source: hdtoday.cc / General streaming content

const hdtodayContent = [
    // HOLLYWOOD MOVIES
    {id: 1, tmdbId: "438631", title: "Dune: Part One", thumbnail: "https://image.tmdb.org/t/p/original/d5NXSklXo0qyIYkgV94XAgMIckC.jpg", year: 2021, genre: ["Sci-Fi", "Adventure"], rating: 95, description: "Paul Atreides debe viajar al planeta más peligroso del universo.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 2, tmdbId: "603", title: "The Matrix", thumbnail: "https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg", year: 1999, genre: ["Sci-Fi", "Action"], rating: 98, description: "Un hacker descubre la verdadera naturaleza de su realidad.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 3, tmdbId: "155", title: "The Dark Knight", thumbnail: "https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg", year: 2008, genre: ["Action", "Crime"], rating: 94, description: "Batman enfrenta al Joker en Gotham City.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 4, tmdbId: "278", title: "The Shawshank Redemption", thumbnail: "https://image.tmdb.org/t/p/original/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg", year: 1994, genre: ["Drama"], rating: 99, description: "La historia de redención de un banquero en prisión.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 5, tmdbId: "299534", title: "Avengers: Endgame", thumbnail: "https://image.tmdb.org/t/p/original/or06FN3Dka5tukK1e9sl16pB3iy.jpg", year: 2019, genre: ["Action", "Sci-Fi"], rating: 88, description: "Los Avengers se reúnen para deshacer las acciones de Thanos.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday", producer: "Disney"},
    {id: 6, tmdbId: "19995", title: "Avatar", thumbnail: "https://image.tmdb.org/t/p/original/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg", year: 2009, genre: ["Sci-Fi", "Adventure"], rating: 94, description: "Un marine parapléjico es enviado a Pandora.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 7, tmdbId: "27205", title: "Inception", thumbnail: "https://image.tmdb.org/t/p/original/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg", year: 2010, genre: ["Sci-Fi", "Thriller"], rating: 96, description: "Un ladrón que roba secretos a través de los sueños.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 8, tmdbId: "13", title: "Forrest Gump", thumbnail: "https://image.tmdb.org/t/p/original/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg", year: 1994, genre: ["Drama", "Romance"], rating: 93, description: "La extraordinaria vida de Forrest Gump.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 9, tmdbId: "497", title: "The Green Mile", thumbnail: "https://image.tmdb.org/t/p/original/velWPhVMQeQKcxggNEU8YmIo52R.jpg", year: 1999, genre: ["Drama", "Fantasy"], rating: 91, description: "Un guardia descubre un don sobrenatural en un prisionero.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 10, tmdbId: "550", title: "Fight Club", thumbnail: "https://image.tmdb.org/t/p/original/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg", year: 1999, genre: ["Drama", "Thriller"], rating: 92, description: "Un oficinista forma un club de lucha clandestino.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},

    // ANIME
    {id: 16, tmdbId: "129", title: "Spirited Away", thumbnail: "https://image.tmdb.org/t/p/original/39wmItIWsg5sZMyRUKGnSxQbUgZ.jpg", year: 2001, genre: ["Anime", "Fantasy"], rating: 99, description: "Una niña queda atrapada en un mundo de espíritus.", region: "Asia", country: "Japón", type: "anime", source: "hdtoday"},
    {id: 17, tmdbId: "4935", title: "Howl's Moving Castle", thumbnail: "https://image.tmdb.org/t/p/original/6pZgXH2S3kQ77262Moq3Y1BsN7d.jpg", year: 2004, genre: ["Anime", "Fantasy"], rating: 91, description: "Sophie busca romper la maldición de una bruja.", region: "Asia", country: "Japón", type: "anime", source: "hdtoday"},
    {id: 18, tmdbId: "569094", title: "Spider-Man: Across the Spider-Verse", thumbnail: "https://image.tmdb.org/t/p/original/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg", year: 2023, genre: ["Animation", "Action"], rating: 97, description: "Miles Morales viaja a través del multiverso.", region: "US", country: "Estados Unidos", type: "anime", source: "hdtoday"},

    // EUROPEAN CINEMA
    {id: 30, tmdbId: "675353", title: "Sonic the Hedgehog 2", thumbnail: "https://image.tmdb.org/t/p/original/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg", year: 2022, genre: ["Action", "Adventure"], rating: 84, description: "Sonic y Tails se enfrentan a Knuckles y Dr. Robotnik.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 31, tmdbId: "508947", title: "Turning Red", thumbnail: "https://image.tmdb.org/t/p/original/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg", year: 2022, genre: ["Animation", "Comedy"], rating: 89, description: "Una niña se convierte en un panda rojo gigante.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday", producer: "Disney"},

    // STREAMING PLATFORM ORIGINALS
    {id: 126, tmdbId: "94997", title: "House of Cards", thumbnail: "https://image.tmdb.org/t/p/original/rsH6F5K3ZH0p8aWXZJ7KF4W7gWb.jpg", year: 2013, genre: ["Drama", "Thriller"], rating: 93, description: "Un político sin escrúpulos busca el poder absoluto.", region: "US", country: "Estados Unidos", type: "series", producer: "Netflix", source: "hdtoday"},
    {id: 127, tmdbId: "80025", title: "Stranger Things", thumbnail: "https://image.tmdb.org/t/p/original/49WJfeN0moxb9IPfGn8AIqMGskD.jpg", year: 2016, genre: ["Sci-Fi", "Horror"], rating: 96, description: "Un grupo de niños descubre experimentos sobrenaturales.", region: "US", country: "Estados Unidos", type: "series", producer: "Netflix", source: "hdtoday"},
    {id: 129, tmdbId: "80057", title: "Black Mirror", thumbnail: "https://image.tmdb.org/t/p/original/5UaYsGZOFhjFDwQix4y5SIr1YEp.jpg", year: 2011, genre: ["Sci-Fi", "Thriller"], rating: 94, description: "Antología que explora el lado oscuro de la tecnología.", region: "UK", country: "Reino Unido", type: "series", producer: "Netflix", source: "hdtoday"},
    {id: 130, tmdbId: "70523", title: "The Crown", thumbnail: "https://image.tmdb.org/t/p/original/1M876KPjulVwppEpldhdc8V4o68.jpg", year: 2016, genre: ["Drama", "History"], rating: 91, description: "La vida de la Reina Isabel II y la familia real británica.", region: "UK", country: "Reino Unido", type: "series", producer: "Netflix", source: "hdtoday"},
    {id: 138, tmdbId: "88396", title: "The Mandalorian", thumbnail: "https://image.tmdb.org/t/p/original/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg", year: 2019, genre: ["Sci-Fi", "Adventure"], rating: 94, description: "Un cazarrecompensas viaja por la galaxia.", region: "US", country: "Estados Unidos", type: "series", producer: "Disney", source: "hdtoday"},
    {id: 142, tmdbId: "1399", title: "Game of Thrones", thumbnail: "https://image.tmdb.org/t/p/original/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg", year: 2011, genre: ["Fantasy", "Drama"], rating: 96, description: "Familias nobles compiten por el Trono de Hierro.", region: "US", country: "Estados Unidos", type: "series", producer: "HBO", source: "hdtoday"},

    // 2024-2025 BLOCKBUSTERS
    {id: 200, tmdbId: "693134", title: "Dune: Part Two", thumbnail: "https://image.tmdb.org/t/p/original/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg", year: 2024, genre: ["Sci-Fi", "Adventure"], rating: 96, description: "Paul Atreides se une a los Fremen en su guerra contra los Harkonnen.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 201, tmdbId: "823464", title: "Godzilla x Kong: The New Empire", thumbnail: "https://image.tmdb.org/t/p/original/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg", year: 2024, genre: ["Action", "Sci-Fi"], rating: 85, description: "Godzilla y Kong se enfrentan a una amenaza colosal.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 202, tmdbId: "872585", title: "Oppenheimer", thumbnail: "https://image.tmdb.org/t/p/original/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", year: 2023, genre: ["Drama", "History"], rating: 97, description: "La historia del padre de la bomba atómica.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 203, tmdbId: "346698", title: "Barbie", thumbnail: "https://image.tmdb.org/t/p/original/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg", year: 2023, genre: ["Comedy", "Fantasy"], rating: 88, description: "Barbie descubre el mundo real más allá de Barbieland.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 204, tmdbId: "1011985", title: "Kung Fu Panda 4", thumbnail: "https://image.tmdb.org/t/p/original/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg", year: 2024, genre: ["Animation", "Comedy"], rating: 86, description: "Po debe entrenar a un nuevo Guerrero Dragón.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 205, tmdbId: "940551", title: "Migration", thumbnail: "https://image.tmdb.org/t/p/original/ldfCF9RhR40mppkzmftxapaHeTo.jpg", year: 2023, genre: ["Animation", "Comedy"], rating: 84, description: "Una familia de patos emprende un viaje épico.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 206, tmdbId: "1022789", title: "Inside Out 2", thumbnail: "https://image.tmdb.org/t/p/original/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg", year: 2024, genre: ["Animation", "Comedy"], rating: 91, description: "Riley enfrenta nuevas emociones en la adolescencia.", region: "US", country: "Estados Unidos", type: "movie", producer: "Disney", source: "hdtoday"},
    {id: 207, tmdbId: "929590", title: "Civil War", thumbnail: "https://image.tmdb.org/t/p/original/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg", year: 2024, genre: ["Action", "Drama"], rating: 89, description: "Periodistas atraviesan EE.UU. durante una guerra civil.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 208, tmdbId: "653346", title: "Kingdom of the Planet of the Apes", thumbnail: "https://image.tmdb.org/t/p/original/gKkl37BQuKTanygYQG1pyYgLVgf.jpg", year: 2024, genre: ["Sci-Fi", "Adventure"], rating: 87, description: "Generaciones después de César, un nuevo líder simio emerge.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 209, tmdbId: "438148", title: "Minions: The Rise of Gru", thumbnail: "https://image.tmdb.org/t/p/original/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg", year: 2022, genre: ["Animation", "Comedy"], rating: 85, description: "La historia de cómo Gru conoció a los Minions.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},
    {id: 210, tmdbId: "960704", title: "The Fall Guy", thumbnail: "https://image.tmdb.org/t/p/original/tSz1qsmSJon0rqjHBxXZmrotuse.jpg", year: 2024, genre: ["Action", "Comedy"], rating: 87, description: "Un doble de acción busca a una estrella de cine desaparecida.", region: "US", country: "Estados Unidos", type: "movie", source: "hdtoday"},

    // MORE ANIME 2023-2024
    {id: 220, tmdbId: "508883", title: "Suzume", thumbnail: "https://image.tmdb.org/t/p/original/6lACnAFLPpSJOYTnckKE8iEp7T6.jpg", year: 2022, genre: ["Anime", "Fantasy"], rating: 93, description: "Una joven viaja por Japón cerrando puertas místicas.", region: "Asia", country: "Japón", type: "anime", source: "hdtoday"},
    {id: 221, tmdbId: "1029575", title: "The Boy and the Heron", thumbnail: "https://image.tmdb.org/t/p/original/f7QBKpQxfNd0v1HRcJ9e4zVvl9a.jpg", year: 2023, genre: ["Anime", "Fantasy"], rating: 94, description: "Un niño descubre un mundo fantástico tras la muerte de su madre.", region: "Asia", country: "Japón", type: "anime", source: "hdtoday"},
    {id: 222, tmdbId: "945961", title: "Demon Slayer: To the Hashira Training", thumbnail: "https://image.tmdb.org/t/p/original/dLaKLJPDcRVTmUMNWYXWPzHc8sL.jpg", year: 2024, genre: ["Anime", "Action"], rating: 92, description: "Tanjiro continúa su entrenamiento para derrotar a Muzan.", region: "Asia", country: "Japón", type: "anime", source: "hdtoday"},
    {id: 223, tmdbId: "677179", title: "Crunchyroll Movie: Dragon Ball Super: Super Hero", thumbnail: "https://image.tmdb.org/t/p/original/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg", year: 2022, genre: ["Anime", "Action"], rating: 88, description: "Gohan y Piccolo enfrentan a los nuevos androides.", region: "Asia", country: "Japón", type: "anime", source: "hdtoday"},
    {id: 224, tmdbId: "912649", title: "Jujutsu Kaisen 0", thumbnail: "https://image.tmdb.org/t/p/original/3pTwMUEavTzVfyA7Ddi0GtSYQPx.jpg", year: 2021, genre: ["Anime", "Action"], rating: 91, description: "Yuta Okkotsu y su maldición especial enfrentan a Geto.", region: "Asia", country: "Japón", type: "anime", source: "hdtoday"},
    {id: 225, tmdbId: "533535", title: "One Piece Film: Red", thumbnail: "https://image.tmdb.org/t/p/original/m80kPdrmmtEh9wlLroCp0bwUGH0.jpg", year: 2022, genre: ["Anime", "Adventure"], rating: 90, description: "Luffy y su tripulación en un concierto épico.", region: "Asia", country: "Japón", type: "anime", source: "hdtoday"},
    {id: 226, tmdbId: "980078", title: "Spy x Family Code: White", thumbnail: "https://image.tmdb.org/t/p/original/sUGbFvC5JiHaxtIeHUrSQbnDC8u.jpg", year: 2023, genre: ["Anime", "Comedy"], rating: 89, description: "La familia Forger en una misión durante las vacaciones.", region: "Asia", country: "Japón", type: "anime", source: "hdtoday"},

    // POPULAR SERIES 2023-2024
    {id: 230, tmdbId: "84773", title: "The Lord of the Rings: The Rings of Power", thumbnail: "https://image.tmdb.org/t/p/original/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg", year: 2022, genre: ["Fantasy", "Adventure"], rating: 87, description: "La Segunda Edad de la Tierra Media cobra vida.", region: "US", country: "Estados Unidos", type: "series", producer: "Amazon", source: "hdtoday"},
    {id: 231, tmdbId: "94605", title: "Arcane", thumbnail: "https://image.tmdb.org/t/p/original/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg", year: 2021, genre: ["Animation", "Action"], rating: 98, description: "El origen de Jinx y Vi en el universo de League of Legends.", region: "US", country: "Estados Unidos", type: "series", producer: "Netflix", source: "hdtoday"},
    {id: 232, tmdbId: "114479", title: "The Bear", thumbnail: "https://image.tmdb.org/t/p/original/sHFlbKS3WLqMnp9t2ghADIJFnuQ.jpg", year: 2022, genre: ["Drama", "Comedy"], rating: 95, description: "Un chef transforma el restaurante de su familia en Chicago.", region: "US", country: "Estados Unidos", type: "series", producer: "Hulu", source: "hdtoday"},
    {id: 233, tmdbId: "111800", title: "Severance", thumbnail: "https://image.tmdb.org/t/p/original/lFf6LLrQjYldcZItzOkGmMMigP7.jpg", year: 2022, genre: ["Drama", "Thriller"], rating: 94, description: "Empleados separan sus recuerdos del trabajo y la vida.", region: "US", country: "Estados Unidos", type: "series", producer: "Apple", source: "hdtoday"},
    {id: 234, tmdbId: "124834", title: "Wednesday", thumbnail: "https://image.tmdb.org/t/p/original/9PFonBhy4cQy7Jz20NpMygczOkv.jpg", year: 2022, genre: ["Comedy", "Mystery"], rating: 91, description: "Wednesday Addams resuelve misterios en Nevermore Academy.", region: "US", country: "Estados Unidos", type: "series", producer: "Netflix", source: "hdtoday"},
    {id: 235, tmdbId: "100088", title: "The Last of Us", thumbnail: "https://image.tmdb.org/t/p/original/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg", year: 2023, genre: ["Drama", "Horror"], rating: 96, description: "Joel protege a Ellie en un mundo post-apocalíptico.", region: "US", country: "Estados Unidos", type: "series", producer: "HBO", source: "hdtoday"},
    {id: 236, tmdbId: "136166", title: "House of the Dragon", thumbnail: "https://image.tmdb.org/t/p/original/z2yahl2uefxDCl0nogcRBstwruJ.jpg", year: 2022, genre: ["Fantasy", "Drama"], rating: 93, description: "La guerra civil de los Targaryen 200 años antes de GOT.", region: "US", country: "Estados Unidos", type: "series", producer: "HBO", source: "hdtoday"},
    {id: 237, tmdbId: "84958", title: "Loki", thumbnail: "https://image.tmdb.org/t/p/original/voHUmluYmKyleFkTu3lOXQG702u.jpg", year: 2021, genre: ["Sci-Fi", "Fantasy"], rating: 92, description: "Loki enfrenta a la TVA y las variantes del multiverso.", region: "US", country: "Estados Unidos", type: "series", producer: "Disney", source: "hdtoday"},
    {id: 238, tmdbId: "111837", title: "Only Murders in the Building", thumbnail: "https://image.tmdb.org/t/p/original/7NDdCrg1Gxq7YLkKsxiBxGvCLQa.jpg", year: 2021, genre: ["Comedy", "Mystery"], rating: 90, description: "Tres vecinos investigan un asesinato en su edificio.", region: "US", country: "Estados Unidos", type: "series", producer: "Hulu", source: "hdtoday"},
    {id: 239, tmdbId: "84958", title: "The Boys", thumbnail: "https://image.tmdb.org/t/p/original/stTEycfG9928HYGEISBFaG1ngjM.jpg", year: 2019, genre: ["Action", "Comedy"], rating: 93, description: "Vigilantes enfrentan a superhéroes corruptos.", region: "US", country: "Estados Unidos", type: "series", producer: "Amazon", source: "hdtoday"},
    {id: 240, tmdbId: "203057", title: "Shogun", thumbnail: "https://image.tmdb.org/t/p/original/7O4iVfOMQmdCSxhOg1W03cUNSQe.jpg", year: 2024, genre: ["Drama", "History"], rating: 96, description: "Un navegante inglés en el Japón feudal del siglo XVII.", region: "US", country: "Estados Unidos", type: "series", producer: "Hulu", source: "hdtoday"},
    {id: 241, tmdbId: "239770", title: "Fallout", thumbnail: "https://image.tmdb.org/t/p/original/AnsSKR9LuK0T9bSADTmBhk0cCBT.jpg", year: 2024, genre: ["Sci-Fi", "Drama"], rating: 91, description: "Supervivientes en un mundo post-apocalíptico nuclear.", region: "US", country: "Estados Unidos", type: "series", producer: "Amazon", source: "hdtoday"},
    {id: 242, tmdbId: "92782", title: "Squid Game", thumbnail: "https://image.tmdb.org/t/p/original/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg", year: 2021, genre: ["Thriller", "Drama"], rating: 95, description: "Personas desesperadas compiten en juegos infantiles mortales.", region: "Asia", country: "Corea del Sur", type: "series", producer: "Netflix", language: "Coreano", source: "hdtoday"},

    // EUROPEAN CINEMA CLASSICS
    {id: 250, tmdbId: "194", title: "Amélie", thumbnail: "https://image.tmdb.org/t/p/original/nSxDa3M9aMvGVLoItzWTepQ5h5d.jpg", year: 2001, genre: ["Romance", "Comedy"], rating: 89, description: "Una joven parisina cambia la vida de otros.", region: "EU", country: "Francia", type: "movie", source: "hdtoday"},
    {id: 251, tmdbId: "637", title: "Life is Beautiful", thumbnail: "https://image.tmdb.org/t/p/original/74hLDKjD5aGYOotO6esUVaeISa2.jpg", year: 1997, genre: ["Drama", "Comedy"], rating: 95, description: "Un padre protege a su hijo en un campo de concentración.", region: "EU", country: "Italia", type: "movie", source: "hdtoday"},
    {id: 252, tmdbId: "207", title: "The Intouchables", thumbnail: "https://image.tmdb.org/t/p/original/4mFsNQwbD0F237Tx7gAPotd0nbJ.jpg", year: 2011, genre: ["Drama", "Comedy"], rating: 92, description: "Amistad entre un aristócrata y su cuidador.", region: "EU", country: "Francia", type: "movie", source: "hdtoday"},
    {id: 253, tmdbId: "66788", title: "La Casa de Papel", thumbnail: "https://image.tmdb.org/t/p/original/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg", year: 2017, genre: ["Crime", "Thriller"], rating: 91, description: "Un grupo de atracadores toma la Fábrica de Moneda.", region: "EU", country: "España", type: "series", producer: "Netflix", source: "hdtoday"},
    {id: 254, tmdbId: "65930", title: "Elite", thumbnail: "https://image.tmdb.org/t/p/original/3NTAbAiao4JLzFQw6YxP1YZppM8.jpg", year: 2018, genre: ["Drama", "Thriller"], rating: 86, description: "Drama adolescente en un colegio de élite español.", region: "EU", country: "España", type: "series", producer: "Netflix", source: "hdtoday"},

    // LATIN AMERICAN CINEMA
    {id: 260, tmdbId: "13808", title: "City of God", thumbnail: "https://image.tmdb.org/t/p/original/k7eYdcdYEYBxmRfHh9CtC56XZfL.jpg", year: 2002, genre: ["Crime", "Drama"], rating: 96, description: "La vida en las favelas de Río de Janeiro.", region: "LatAm", country: "Brasil", type: "movie", source: "hdtoday"},
    {id: 261, tmdbId: "783", title: "Y Tu Mamá También", thumbnail: "https://image.tmdb.org/t/p/original/7KHkSQ56Z7LXuICwOWMxlQFvPQS.jpg", year: 2001, genre: ["Drama", "Romance"], rating: 86, description: "Dos adolescentes en un viaje por carretera con una mujer mayor.", region: "LatAm", country: "México", type: "movie", source: "hdtoday"},
    {id: 262, tmdbId: "496243", title: "Parasite", thumbnail: "https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", year: 2019, genre: ["Drama", "Thriller"], rating: 98, description: "Una familia pobre se infiltra en la vida de ricos.", region: "Asia", country: "Corea del Sur", type: "movie", source: "hdtoday"},

    // BOLLYWOOD HITS
    {id: 270, tmdbId: "614930", title: "RRR", thumbnail: "https://image.tmdb.org/t/p/original/nEufeZlyAOLqO2brrs0yeF1lgXO.jpg", year: 2022, genre: ["Action", "Drama"], rating: 93, description: "Dos revolucionarios luchan contra el Imperio Británico.", region: "India", country: "India", type: "movie", language: "Hindi", source: "hdtoday"},
    {id: 271, tmdbId: "677959", title: "K.G.F: Chapter 2", thumbnail: "https://image.tmdb.org/t/p/original/80DrQCJ7kqkpUfO7OZMIGnMpXfP.jpg", year: 2022, genre: ["Action", "Drama"], rating: 89, description: "Rocky continúa su dominio de las minas de oro de Kolar.", region: "India", country: "India", type: "movie", language: "Hindi", source: "hdtoday"},
    {id: 272, tmdbId: "13895", title: "3 Idiots", thumbnail: "https://image.tmdb.org/t/p/original/66A9MqXOyVFCssoloscwGJueVjZ.jpg", year: 2009, genre: ["Comedy", "Drama"], rating: 92, description: "Tres amigos cuestionan el sistema educativo indio.", region: "India", country: "India", type: "movie", language: "Hindi", source: "hdtoday"},
    {id: 273, tmdbId: "800356", title: "Pathaan", thumbnail: "https://image.tmdb.org/t/p/original/uxWC7XKZqKd6X0k3qtPBZvnAr9w.jpg", year: 2023, genre: ["Action", "Thriller"], rating: 86, description: "Un agente secreto protege a India de una amenaza terrorista.", region: "India", country: "India", type: "movie", language: "Hindi", source: "hdtoday"},
    {id: 274, tmdbId: "865738", title: "Jawan", thumbnail: "https://image.tmdb.org/t/p/original/jFt1gS9UzTsIoMsV8PAvXRqkCQR.jpg", year: 2023, genre: ["Action", "Thriller"], rating: 88, description: "Un vigilante busca justicia para los oprimidos.", region: "India", country: "India", type: "movie", language: "Hindi", source: "hdtoday"},
    {id: 275, tmdbId: "976573", title: "Animal", thumbnail: "https://image.tmdb.org/t/p/original/hr9rjR7FPmPJp4qvQhbCHqkzUTW.jpg", year: 2023, genre: ["Action", "Crime"], rating: 85, description: "Un hijo busca la aprobación de su padre magnate.", region: "India", country: "India", type: "movie", language: "Hindi", source: "hdtoday"}
];

// Export
if (typeof module !== 'undefined' && module.exports) {
    module.exports = hdtodayContent;
}
