// VidSrc Database - Premium Streaming Content
// Source: vidsrc.xyz / Movies and Series

const vidsrcContent = [
    // HOLLYWOOD BLOCKBUSTERS
    {id: 400, tmdbId: "299534", title: "Avengers: Endgame", thumbnail: "https://image.tmdb.org/t/p/original/or06FN3Dka5tukK1e9sl16pB3iy.jpg", year: 2019, genre: ["Action", "Adventure"], rating: 94, description: "Los Vengadores se reúnen una última vez para revertir el daño de Thanos.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "vidsrc"},
    {id: 401, tmdbId: "438631", title: "Dune", thumbnail: "https://image.tmdb.org/t/p/original/d5NXSklXo0qyIYkgV94XAgMIckC.jpg", year: 2021, genre: ["Sci-Fi", "Adventure"], rating: 92, description: "Un joven noble debe proteger el recurso más valioso del universo.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "vidsrc"},
    {id: 402, tmdbId: "615656", title: "Meg 2: The Trench", thumbnail: "https://image.tmdb.org/t/p/original/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg", year: 2023, genre: ["Action", "Horror"], rating: 85, description: "Jonas Taylor se enfrenta a megalodones y mercenarios.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "vidsrc"},
    {id: 403, tmdbId: "502356", title: "The Super Mario Bros. Movie", thumbnail: "https://image.tmdb.org/t/p/original/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg", year: 2023, genre: ["Animation", "Adventure"], rating: 88, description: "Mario y Luigi viajan por el Reino Champiñón.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "vidsrc"},
    {id: 404, tmdbId: "569094", title: "Spider-Man: Across the Spider-Verse", thumbnail: "https://image.tmdb.org/t/p/original/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg", year: 2023, genre: ["Animation", "Action"], rating: 96, description: "Miles Morales viaja a través del multiverso.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "vidsrc"},
    {id: 405, tmdbId: "298618", title: "The Flash", thumbnail: "https://image.tmdb.org/t/p/original/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg", year: 2023, genre: ["Action", "Adventure"], rating: 83, description: "Barry Allen viaja en el tiempo para salvar a su familia.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "vidsrc"},
    {id: 406, tmdbId: "507089", title: "Five Nights at Freddy's", thumbnail: "https://image.tmdb.org/t/p/original/A4j8S6moJS2zNtRR8oWF08gRnL5.jpg", year: 2023, genre: ["Horror", "Mystery"], rating: 80, description: "Un guardia de seguridad enfrenta animatrónicos poseídos.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "vidsrc"},
    {id: 407, tmdbId: "76600", title: "Avatar: The Way of Water", thumbnail: "https://image.tmdb.org/t/p/original/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg", year: 2022, genre: ["Sci-Fi", "Adventure"], rating: 93, description: "Jake Sully y su familia exploran las regiones de Pandora.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "vidsrc"},
    {id: 408, tmdbId: "436270", title: "Black Adam", thumbnail: "https://image.tmdb.org/t/p/original/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg", year: 2022, genre: ["Action", "Fantasy"], rating: 81, description: "Un antiguo esclavo obtiene los poderes de los dioses.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "vidsrc"},
    {id: 409, tmdbId: "505642", title: "Black Panther: Wakanda Forever", thumbnail: "https://image.tmdb.org/t/p/original/sv1xJUazXeYqALzczSZ3O6nkH75.jpg", year: 2022, genre: ["Action", "Adventure"], rating: 89, description: "Los líderes de Wakanda luchan por proteger su nación.", region: "Hollywood", country: "Estados Unidos", type: "movie", language: "Inglés", source: "vidsrc"},

    // SERIES
    {id: 420, tmdbId: "94997", title: "House of the Dragon", thumbnail: "https://image.tmdb.org/t/p/original/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg", year: 2022, genre: ["Drama", "Fantasy"], rating: 92, description: "Precuela de Game of Thrones sobre la casa Targaryen.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "vidsrc"},
    {id: 421, tmdbId: "84958", title: "Loki", thumbnail: "https://image.tmdb.org/t/p/original/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg", year: 2021, genre: ["Sci-Fi", "Adventure"], rating: 91, description: "Loki viaja a través del tiempo tras robar el Teseracto.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "vidsrc"},
    {id: 422, tmdbId: "85271", title: "WandaVision", thumbnail: "https://image.tmdb.org/t/p/original/glKDfE6btIRcVB5zrjspRIs4r52.jpg", year: 2021, genre: ["Drama", "Sci-Fi"], rating: 90, description: "Wanda y Vision viven en una realidad de sitcoms.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "vidsrc"},
    {id: 423, tmdbId: "88396", title: "The Falcon and the Winter Soldier", thumbnail: "https://image.tmdb.org/t/p/original/6kbAMLteGO8yyewYau6bJ683sw7.jpg", year: 2021, genre: ["Action", "Adventure"], rating: 88, description: "Sam Wilson y Bucky Barnes se unen en una aventura.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "vidsrc"},
    {id: 424, tmdbId: "92830", title: "The Last of Us", thumbnail: "https://image.tmdb.org/t/p/original/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg", year: 2023, genre: ["Drama", "Sci-Fi"], rating: 95, description: "Joel y Ellie viajan por Estados Unidos en un apocalipsis.", region: "Hollywood", country: "Estados Unidos", type: "series", language: "Inglés", source: "vidsrc"}
];

// Export
if (typeof module !== 'undefined' && module.exports) {
    module.exports = vidsrcContent;
}
